version: '3.8'

services:
  redis:
    image: redis:latest
    env_file: 
      - stack.env
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - internal_network

  postgres:
    image: postgres:18
    env_file: 
      - stack.env
    volumes:
      - postgresql-data:/var/lib/postgresql
    restart: always
    networks:
      - internal_network

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    env_file: 
      - stack.env
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    restart: always
    networks:
      - internal_network

  telegram-bili-feed-helper:
    image: ghcr.io/simonsmh/telegram-bili-feed-helper:master
    depends_on:
      - redis
      - postgres
      - telegram-bot-api
    env_file: 
      - stack.env
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    restart: always
    networks:
      - internal_network

volumes:
  redis-data:
  postgresql-data:
  telegram-bot-api-data:

networks:
  internal_network:
    driver: bridge
